services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pessoas
    ports:
      - '5432:5432'
    command: "postgres -c max_connections=200 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
#      - ./postgresql.conf:/etc/postgresql/postgresql.conf
#    command: postgres -c config_file=/etc/postgresql/postgresql.conf
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: '1500M'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d pessoas -h localhost" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    network_mode: host

  app1:
    image: quarkus/rinha-backend-v2:latest
#    build:
#      context: .
#      dockerfile: src/main/docker/Dockerfile.native
#    ports:
#      - '8080:8080'
    environment:
      - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://localhost:5432/pessoas
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=admin
      - QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE=25
      - QUARKUS_LOG_CONSOLE_ENABLE=false
      - QUARKUS_LOG_FILE_ENABLE=false
      - QUARKUS_DATASOURCE_REACTIVE_IDLE_TIMEOUT=5
    depends_on:
      postgres-db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: '512MB'
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:8080/ || exit 1
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 5s
    network_mode: host

  app2:
    image: quarkus/rinha-backend-v2:latest
#    build:
#      context: .
#      dockerfile: src/main/docker/Dockerfile.native
#    ports:
#      - '8090:8080'
    environment:
      - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://localhost:5432/pessoas
      - QUARKUS_HTTP_PORT=8090
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=admin
      - QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE=25
      - QUARKUS_LOG_CONSOLE_ENABLE=false
      - QUARKUS_LOG_FILE_ENABLE=false
      - QUARKUS_DATASOURCE_REACTIVE_IDLE_TIMEOUT=5
    depends_on:
      postgres-db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: '512MB'
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:8090/ || exit 1
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 5s
    network_mode: host

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
    network_mode: host
#    deploy:
#      resources:
#        limits:
#          cpus: '0.25'
#          memory: '1500M'

#  pg-admin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "emanuel@gmail.com"
#      PGADMIN_DEFAULT_PASSWORD: "emanuel"
#    ports:
#      - '16543:80'
#    depends_on:
#      - postgres-db
#    networks:
#      - app-network

volumes:
  postgres_data:
    driver: local

#networks:
#  app-network:
#    driver: bridge

