services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pessoas
    ports:
      - '5432:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "emanuel@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db

volumes:
  postgres_data:
    driver: local